function Hd = bandpass_filt_order(Fs,N,Fstop1,Fpass1,Fpass2,Fstop2)
%BANDPASS_FILT_ORDER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
% Generated on: 03-May-2014 07:02:23

% FIR least-squares Bandpass filter designed using the FIRLS function.

% All frequency values are in Hz.
% Fs = 48000;  % Sampling Frequency
% 
% N      = 180;    % Order
% Fstop1 = 7200;   % First Stopband Frequency
% Fpass1 = 9600;   % First Passband Frequency
% Fpass2 = 12000;  % Second Passband Frequency
% Fstop2 = 14400;  % Second Stopband Frequency
Wstop1 = 1;      % First Stopband Weight
Wpass  = 1;      % Passband Weight
Wstop2 = 1;      % Second Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
    0], [Wstop1 Wpass Wstop2]);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
