function Hd = lowpass_filt(Fs,Fpass,Fstop,Stop_db)
%LOWPASS_FILT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
% Generated on: 03-May-2014 04:34:26

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
% Fs = 48000;  % Sampling Frequency

% Fpass = 9600;            % Passband Frequency
% Fstop = 12000;           % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop =10^(-(Stop_db/20));          % Stopband Attenuation
flag  = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fpass Fstop]/(Fs/2), [1 0], [Dstop Dpass]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
